services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      #      Cette ligne est temporairement supprimée pour forcer la réinitialisation
      #      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=mediscreen

  patient-service:
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    container_name: patient-service
    ports:
      - "8081:8081"

  note-service:
    build:
      context: .
      dockerfile: note-service/Dockerfile
    container_name: note-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo

  diabetes-report-service:
    build:
      context: .
      dockerfile: diabetes-report-service/Dockerfile
    container_name: diabetes-report-service
    ports:
      - "8083:8083"

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway-service
    ports:
      - "8090:8080" # On utilise le port 8090 car 8080 est pris
    depends_on:
      - patient-service
      - note-service
      - diabetes-report-service

  front-service:
    build:
      context: .
      dockerfile: front-service/Dockerfile
    container_name: front-service
    ports:
      - "5173:80"
    depends_on:
      - gateway-service

volumes:
  mongo_data: